---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "easytrade.labels" . | nindent 4 }}
    istio-injection: {{ .Values.global.enableIstio | default "enabled" }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.global.namespace }}-quota
  namespace: {{ .Values.global.namespace }}
spec:
  hard:
    requests.cpu: "16"
    requests.memory: "32Gi"
    limits.cpu: "32"
    limits.memory: "64Gi"
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.global.namespace }}-limits
  namespace: {{ .Values.global.namespace }}
spec:
  limits:
    - default:
        cpu: "1"
        memory: "1Gi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      type: Container
