workspaceName: synapse-workspace-prod
LS_AzureKeyVault_properties_typeProperties_baseUrl: https://kv-synapse-prod.vault.azure.net/
WorkspaceDefaultStorage_properties_typeProperties_url: https://synapseproddatalake.dfs.core.windows.net
BigDataPool_properties_typeProperties_sparkPool_referenceName: sparkpoolprod
