# template and azure-pipeline simple

# template file docker-build-push-template.yml

parameters:
  javaVersion: '11'
  osType: 'RHEL 7'
  dockerfilePath: 'Dockerfile'
  dockerImageName: ''
  nexusRepositoryUrl: ''
  nexusUsername: ''
  nexusPassword: ''

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: |
      echo "Building Docker image with Java version: ${{ parameters.javaVersion }} and OS type: ${{ parameters.osType }}"
      docker build --build-arg JDK_VERSION=${{ parameters.javaVersion }} -t ${{ parameters.dockerImageName }} -f ${{ parameters.dockerfilePath }} .
    displayName: 'Build Docker image'

  - script: |
      echo "Logging into Nexus Repository Manager"
      docker login -u ${{ parameters.nexusUsername }} -p ${{ parameters.nexusPassword }} ${{ parameters.nexusRepositoryUrl }}

      echo "Pushing Docker image to Nexus Repository Manager"
      docker push ${{ parameters.dockerImageName }}
    displayName: 'Push Docker image to Nexus Repository Manager'



#
# azure-pipelines.yml

trigger:
  branches:
    include:
    - '*'

resources:
  repositories:
  - repository: ado-seed-pipelines
    type: git
    name: '<your-organization>/<your-project>/ado-seed-pipelines'
    ref: refs/heads/main

variables:
  javaVersion: '11'
  osType: 'RHEL 7'
  dockerImageName: 'your-docker-image-name'
  nexusRepositoryUrl: 'https://your-nexus-url/repository/your-docker-repo/'
  nexusUsername: 'your-nexus-username'
  nexusPassword: 'your-nexus-password'

jobs:
- template: docker-build-push-template.yml@ado-seed-pipelines
  parameters:
    javaVersion: $(javaVersion)
    osType: $(osType)
    dockerImageName: $(dockerImageName)
    nexusRepositoryUrl: $(nexusRepositoryUrl)
    nexusUsername: $(nexusUsername)
    nexusPassword: $(nexusPassword)
