#!/bin/bash
# generate-heredoc-workflow.sh - Interactive workflow generator
# Creates custom GitHub Actions workflows with HEREDOC file generation

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

info() { echo -e "${BLUE}ℹ${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }
section() { echo -e "\n${BOLD}${BLUE}▶ $*${NC}\n"; }

prompt() {
    local var_name=$1
    local prompt_text=$2
    local default_value=${3:-}
    
    if [ -n "$default_value" ]; then
        read -rp "$(echo -e "${BLUE}?${NC}") $prompt_text [$default_value]: " value
        eval "$var_name=\"${value:-$default_value}\""
    else
        read -rp "$(echo -e "${BLUE}?${NC}") $prompt_text: " value
        eval "$var_name=\"$value\""
    fi
}

main() {
    echo ""
    echo -e "${BOLD}════════════════════════════════════════════${NC}"
    echo -e "${BOLD}  HEREDOC Workflow Generator${NC}"
    echo -e "${BOLD}════════════════════════════════════════════${NC}"
    echo ""
    
    info "This will help you create a custom GitHub Actions workflow"
    info "that generates files using HEREDOC scripts."
    echo ""
    
    # Collect information
    section "Workflow Configuration"
    
    prompt WORKFLOW_NAME "Workflow name" "generate-files"
    prompt WORKFLOW_DESC "Workflow description" "Generate files using HEREDOC"
    prompt TRIGGER_TYPE "Trigger type (dispatch/push/schedule)" "dispatch"
    prompt DIRECTORY_NAME "Output directory name" "generated-files"
    prompt BRANCH_NAME "Branch name for changes" "auto-generated"
    
    section "Files to Generate"
    
    FILES=()
    while true; do
        echo ""
        prompt ADD_FILE "Add a file to generate? (y/n)" "y"
        
        if [[ ! "$ADD_FILE" =~ ^[Yy] ]]; then
            break
        fi
        
        prompt FILE_NAME "File name (with extension)"
        prompt FILE_TYPE "File type (config/script/doc/other)"
        prompt FILE_DESC "File description"
        
        FILES+=("$FILE_NAME|$FILE_TYPE|$FILE_DESC")
        success "Added: $FILE_NAME"
    done
    
    if [ ${#FILES[@]} -eq 0 ]; then
        warn "No files specified, adding example file"
        FILES=("README.md|doc|Example documentation")
    fi
    
    section "Target Repository"
    
    prompt TARGET_CURRENT "Generate in current repo? (y/n)" "y"
    
    if [[ "$TARGET_CURRENT" =~ ^[Yy] ]]; then
        TARGET_MODE="current"
    else
        TARGET_MODE="target"
    fi
    
    section "Options"
    
    prompt CREATE_PR "Create pull request? (y/n)" "y"
    prompt VALIDATE_FILES "Add validation step? (y/n)" "y"
    
    # Generate workflow
    section "Generating Workflow"
    
    WORKFLOW_FILE=".github/workflows/${WORKFLOW_NAME}.yml"
    mkdir -p "$(dirname "$WORKFLOW_FILE")"
    
    generate_workflow > "$WORKFLOW_FILE"
    
    success "Workflow generated: $WORKFLOW_FILE"
    
    # Summary
    section "Summary"
    
    echo "Workflow: $WORKFLOW_NAME"
    echo "Directory: $DIRECTORY_NAME"
    echo "Files: ${#FILES[@]}"
    echo "Target: $TARGET_MODE"
    echo "Create PR: $CREATE_PR"
    echo ""
    
    info "To use this workflow:"
    echo ""
    echo "  git add $WORKFLOW_FILE"
    echo "  git commit -m 'Add $WORKFLOW_NAME workflow'"
    echo "  git push"
    echo ""
    
    if [[ "$TRIGGER_TYPE" == "dispatch" ]]; then
        echo "  gh workflow run $WORKFLOW_NAME.yml"
    fi
    
    echo ""
}

generate_workflow() {
    cat <<EOF
name: $WORKFLOW_DESC

# Generated by generate-heredoc-workflow.sh
# Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

on:
EOF

    case "$TRIGGER_TYPE" in
        dispatch)
            cat <<'EOF'
  workflow_dispatch:
    inputs:
EOF
            if [[ "$TARGET_MODE" == "target" ]]; then
                cat <<'EOF'
      target_repo:
        description: 'Target repository (owner/repo)'
        required: true
        type: string
EOF
            fi
            cat <<EOF
      branch_name:
        description: 'Branch name for changes'
        required: false
        default: '$BRANCH_NAME'
        type: string
EOF
            ;;
        push)
            cat <<'EOF'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
EOF
            ;;
        schedule)
            cat <<'EOF'
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:
EOF
            ;;
    esac

    cat <<'EOF'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-files:
    runs-on: ubuntu-latest
    
    steps:
EOF

    if [[ "$TARGET_MODE" == "target" ]]; then
        cat <<'EOF'
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.target_repo }}
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          fetch-depth: 0
EOF
    else
        cat <<'EOF'
      - name: Checkout
        uses: actions/checkout@v4
EOF
    fi

    cat <<'EOF'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
EOF

    if [[ "$CREATE_PR" =~ ^[Yy] ]]; then
        cat <<EOF

      - name: Create Branch
        run: |
          BRANCH="\${{ github.event.inputs.branch_name || '$BRANCH_NAME' }}"
          git push origin --delete "\$BRANCH" 2>/dev/null || true
          git checkout -b "\$BRANCH"
EOF
    fi

    cat <<EOF

      - name: Create Directory
        run: mkdir -p $DIRECTORY_NAME
EOF

    # Generate file creation steps
    for i in "${!FILES[@]}"; do
        IFS='|' read -r fname ftype fdesc <<< "${FILES[$i]}"
        
        cat <<EOF

      - name: Generate File $((i+1)) - $fname
        run: |
          cat > $DIRECTORY_NAME/$fname <<'EOF_FILE'
EOF
        
        generate_file_content "$fname" "$ftype" "$fdesc"
        
        cat <<'EOF'
          EOF_FILE
          
EOF
        
        if [[ "$fname" == *.sh ]]; then
            echo "          chmod +x $DIRECTORY_NAME/$fname"
            echo ""
        fi
        
        echo "          echo \"✓ Generated $fname\""
    done

    if [[ "$VALIDATE_FILES" =~ ^[Yy] ]]; then
        cat <<EOF

      - name: Validate Generated Files
        run: |
          echo "Validating generated files..."
          
          for file in $DIRECTORY_NAME/*; do
            if [ -f "\$file" ]; then
              echo "  ✓ \$(basename "\$file")"
            fi
          done
          
          # Additional validation
          if command -v jq >/dev/null 2>&1; then
            for json in $DIRECTORY_NAME/*.json; do
              [ -f "\$json" ] && jq empty "\$json" && echo "  ✓ Valid JSON: \$json"
            done
          fi
EOF
    fi

    cat <<EOF

      - name: Commit Changes
        run: |
          git add $DIRECTORY_NAME/
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> \$GITHUB_ENV
            exit 0
          fi
          
          git commit -m "Generate files in $DIRECTORY_NAME/

Generated by: GitHub Actions
Workflow: $WORKFLOW_NAME
Timestamp: \$(date -u +'%Y-%m-%d %H:%M:%S UTC')

Files:
EOF

    for i in "${!FILES[@]}"; do
        IFS='|' read -r fname ftype fdesc <<< "${FILES[$i]}"
        echo "- $fname - $fdesc"
    done

    cat <<'EOF'
"
          
          echo "has_changes=true" >> $GITHUB_ENV
EOF

    if [[ "$CREATE_PR" =~ ^[Yy] ]]; then
        cat <<EOF

      - name: Push Branch
        if: env.has_changes == 'true'
        run: |
          BRANCH="\${{ github.event.inputs.branch_name || '$BRANCH_NAME' }}"
          git push origin "\$BRANCH" --force

      - name: Create Pull Request
        if: env.has_changes == 'true'
        run: |
          gh pr create \\
            --title "Generate files in $DIRECTORY_NAME/" \\
            --body "## Generated Files

This PR contains automatically generated files.

### Files Generated

EOF

        for i in "${!FILES[@]}"; do
            IFS='|' read -r fname ftype fdesc <<< "${FILES[$i]}"
            echo "- \`$fname\` - $fdesc"
        done

        cat <<'EOF'

### Details

- Directory: \`$DIRECTORY_NAME/\`
- Generated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
- Workflow: $WORKFLOW_NAME

---

*Automatically generated by GitHub Actions*" \
            --base main \
            --head "${{ github.event.inputs.branch_name || '$BRANCH_NAME' }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
EOF
    else
        cat <<'EOF'

      - name: Push Changes
        if: env.has_changes == 'true'
        run: git push
EOF
    fi
}

generate_file_content() {
    local fname=$1
    local ftype=$2
    local fdesc=$3
    
    case "$fname" in
        *.md)
            cat <<'CONTENT'
# Generated Documentation

This file was automatically generated.

## Description

[Add description here]

## Usage

[Add usage instructions]

## Generated

- Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
- Workflow: GitHub Actions

CONTENT
            ;;
        *.json)
            cat <<'CONTENT'
{
  "name": "generated-config",
  "version": "1.0.0",
  "description": "Auto-generated configuration",
  "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "settings": {
    "enabled": true,
    "timeout": 30
  }
}
CONTENT
            ;;
        *.yml|*.yaml)
            cat <<'CONTENT'
version: 1.0
metadata:
  name: generated-config
  description: Auto-generated YAML configuration
  generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)

settings:
  enabled: true
  timeout: 30
CONTENT
            ;;
        *.sh)
            cat <<'CONTENT'
#!/bin/bash
# Generated script

set -euo pipefail

echo "This is a generated script"
echo "Customize the content in the workflow"

# Add your script logic here
CONTENT
            ;;
        *.txt)
            cat <<'CONTENT'
Generated Text File
===================

This file was automatically generated by GitHub Actions.

Date: $(date)
Description: [Add description]

Add your content here.
CONTENT
            ;;
        *)
            cat <<'CONTENT'
# Generated File

This file was automatically generated.

Add your content here.
CONTENT
            ;;
    esac
}

main "$@"
