#!/usr/bin/env bash
# Generated by foundry-byok. Do not edit; change the inventory and regenerate.
#
# Direct API calls for Azure AI Foundry deployment 'gpt-oss-120b'
#   environment : dev
#   host        : fdy-myass-dev-eus2.openai.azure.com
#   model ID    : gpt-oss-120b
#   surface     : openai-v1 (preferred wire API: completions)
#
# Usage: ./curl.sh [models|chat|responses|legacy|all]
#
# Auth (first match wins):
#   AZURE_FOUNDRY_BEARER_TOKEN  Entra ID token for scope https://cognitiveservices.azure.com/.default
#   FOUNDRY_DEV_API_KEY  resource API key
# Get a token with:
#   az account get-access-token --resource https://cognitiveservices.azure.com --query accessToken -o tsv
set -euo pipefail

PROMPT="${PROMPT:-Reply with the single word: pong}"

if [[ -n "${AZURE_FOUNDRY_BEARER_TOKEN:-}" ]]; then
  AUTH_HEADER="Authorization: Bearer ${AZURE_FOUNDRY_BEARER_TOKEN}"
elif [[ -n "${FOUNDRY_DEV_API_KEY:-}" ]]; then
  AUTH_HEADER="api-key: ${FOUNDRY_DEV_API_KEY}"
else
  echo "error: export AZURE_FOUNDRY_BEARER_TOKEN or FOUNDRY_DEV_API_KEY" >&2
  exit 2
fi

# -M keeps jq output free of ANSI colour codes when it is captured by CI.
pretty() { if command -v jq >/dev/null 2>&1; then jq -M .; else cat; fi; }

call() { # call METHOD URL [BODY]
  local method="$1" url="$2" body="${3:-}"
  local args=(-sS --fail-with-body --max-time 120 -X "$method" "$url" -H "$AUTH_HEADER")
  if [[ -n "$body" ]]; then args+=(-H "Content-Type: application/json" --data "$body"); fi
  echo ">>> $method $url" >&2
  curl "${args[@]}" | pretty
}

json_prompt() { printf '%s' "$PROMPT" | if command -v jq >/dev/null 2>&1; then jq -MRs .; else sed 's/\\/\\\\/g; s/"/\\"/g; s/^/"/; s/$/"/'; fi; }

# GET /openai/v1/models lists the model IDs this resource exposes. gh-aw's
# engine.model must be one of them (gpt-oss-120b is expected).
do_models() { call GET 'https://fdy-myass-dev-eus2.openai.azure.com/openai/v1/models'; }

# v1 API: unversioned URL; the *deployment name* travels in "model".
do_chat() {
  call POST 'https://fdy-myass-dev-eus2.openai.azure.com/openai/v1/chat/completions' "$(cat <<JSON
{"model": "gpt-oss-120b",
 "messages": [{"role": "user", "content": $(json_prompt)}]}
JSON
)"
}

do_responses() {
  call POST 'https://fdy-myass-dev-eus2.openai.azure.com/openai/v1/responses' "$(cat <<JSON
{"model": "gpt-oss-120b", "input": $(json_prompt)}
JSON
)"
}

# Legacy API: deployment name in the path, api-version required, no "model".
do_legacy() {
  call POST 'https://fdy-myass-dev-eus2.openai.azure.com/openai/deployments/gpt-oss-120b/chat/completions?api-version=2024-10-21' "$(cat <<JSON
{"messages": [{"role": "user", "content": $(json_prompt)}]}
JSON
)"
}

case "${1:-chat}" in
  models)    do_models ;;
  chat)      do_chat ;;
  responses) do_responses ;;
  legacy)    do_legacy ;;
  all)       do_models; do_chat; do_responses; do_legacy ;;
  *) echo "usage: $0 [models|chat|responses|legacy|all]" >&2; exit 2 ;;
esac
